version: '3.9'

services:
  api:
    build: .
    ports:
      - '8080:8080'
    container_name: api
    working_dir: /api
    volumes:
      - './api:/api'
    environment:
      TZ: Asia/Tokyo
    command: [sh, -c, uvicorn main:app --reload --host 0.0.0.0 --port 8080]