version: '3.9'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: app
    working_dir: /app
    volumes:
      - './app:/app'
    environment:
      TZ: Asia/Tokyo
    command: [sh, -c, uvicorn main:app --reload --host 0.0.0.0 --port 8080]